version: '3.8'

services:
  # Service PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ecole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  # Service Spring Boot
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecole
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgre
    depends_on:
      - db
    networks:
      - spring-network
    restart: on-failure

# Définitions des volumes et réseaux
volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge